//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITO5032_Assignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int id { get; set; }
        public string start_datetime { get; set; }
        public string end_datetime { get; set; }
        public int User_id { get; set; }
        public int Bookable_id { get; set; }
    
        public virtual AppUser User { get; set; }
        public virtual Bookable Bookable { get; set; }
    }
}
