//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITO5032_Assignment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Booking
    {
        [Required]
        public int id { get; set; }
        [Required]
        [Display(Name = "Start Date Time")]
        public System.DateTime start_datetime { get; set; }
        [Required]
        [Display(Name = "End Date Time")]
        public System.DateTime end_datetime { get; set; }
        [Required]
        [Display(Name = "User")]
        public int User_id { get; set; }
        [Required]
        [Display(Name = "Bookable")]
        public int Bookable_id { get; set; }
    
        public virtual AppUser User { get; set; }
        public virtual Bookable Bookable { get; set; }
    }
}
