//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITO5032_Assignment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class File
    {
        [Required]
        public int id { get; set; }
        [Required]
        [Display(Name = "File Name")]
        public string file_name { get; set; }
        [Required]
        [Display(Name = "File Location")]
        public string file_location { get; set; }
    }
}
