//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITO5032_Assignment.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelsContainer : DbContext
    {
        public ModelsContainer()
            : base("name=ModelsContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppUser> AppUsers { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Rating> Ratings { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<Bookable> Bookables { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
    }
}
