namespace ITO5032_Assignment.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class migration8 : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.Bookings", "User_id1", "dbo.AppUsers");
            DropForeignKey("dbo.Notifications", "User_id1", "dbo.AppUsers");
            DropForeignKey("dbo.Ratings", "AppUser_id", "dbo.AppUsers");
            DropForeignKey("dbo.Bookings", "Bookable_id1", "dbo.Bookables");
            DropForeignKey("dbo.Bookables", "Location_id1", "dbo.Locations");
            DropForeignKey("dbo.Locations", "file_id1", "dbo.Files");
            DropForeignKey("dbo.Ratings", "User_id1", "dbo.AppUsers");
            DropIndex("dbo.Bookings", new[] { "Bookable_id1" });
            DropIndex("dbo.Bookings", new[] { "User_id1" });
            DropIndex("dbo.Bookables", new[] { "Location_id1" });
            DropIndex("dbo.Locations", new[] { "file_id1" });
            DropIndex("dbo.Notifications", new[] { "User_id1" });
            DropIndex("dbo.Ratings", new[] { "Service_Provider_id" });
            DropIndex("dbo.Ratings", new[] { "User_id1" });
            DropIndex("dbo.Ratings", new[] { "AppUser_id" });
            AddColumn("dbo.Bookings", "AppUser_id", c => c.Int());
            AddColumn("dbo.Bookings", "Bookable_id2", c => c.Int());
            AddColumn("dbo.Bookings", "Bookable_id3", c => c.Int());
            AddColumn("dbo.Bookings", "Bookable_id4", c => c.Int());
            AddColumn("dbo.Bookings", "Bookable1_id", c => c.Int());
            AddColumn("dbo.Bookings", "User_id2", c => c.Int());
            AddColumn("dbo.Bookings", "AppUser_id1", c => c.Int());
            AddColumn("dbo.Bookings", "AppUser_id2", c => c.Int());
            AddColumn("dbo.Bookables", "Location_id2", c => c.Int());
            AddColumn("dbo.Bookables", "Location_id3", c => c.Int());
            AddColumn("dbo.Bookables", "Location_id4", c => c.Int());
            AddColumn("dbo.Bookables", "Location1_id", c => c.Int());
            AddColumn("dbo.Locations", "file_id2", c => c.Int());
            AddColumn("dbo.Notifications", "AppUser_id", c => c.Int());
            AddColumn("dbo.Notifications", "User_id2", c => c.Int());
            AddColumn("dbo.Notifications", "AppUser_id1", c => c.Int());
            AddColumn("dbo.Notifications", "AppUser_id2", c => c.Int());
            AddColumn("dbo.Ratings", "AppUser_id1", c => c.Int());
            AddColumn("dbo.Ratings", "User_id2", c => c.Int());
            AddColumn("dbo.Ratings", "AppUser_id2", c => c.Int());
            AddColumn("dbo.Ratings", "AppUser_id3", c => c.Int());
            AlterColumn("dbo.AppUsers", "first_name", c => c.String());
            AlterColumn("dbo.AppUsers", "last_name", c => c.String());
            AlterColumn("dbo.AppUsers", "password", c => c.String());
            AlterColumn("dbo.Bookables", "name", c => c.String());
            AlterColumn("dbo.Bookables", "description", c => c.String());
            AlterColumn("dbo.Bookables", "available_day", c => c.String());
            AlterColumn("dbo.Bookables", "available_start_time", c => c.String());
            AlterColumn("dbo.Bookables", "available_end_time", c => c.String());
            AlterColumn("dbo.Bookables", "max_occupancy", c => c.String());
            AlterColumn("dbo.Bookables", "booking_type", c => c.String());
            AlterColumn("dbo.Locations", "address1", c => c.String());
            AlterColumn("dbo.Locations", "address2", c => c.String());
            AlterColumn("dbo.Locations", "room", c => c.String());
            AlterColumn("dbo.Files", "file_name", c => c.String());
            AlterColumn("dbo.Files", "file_location", c => c.String());
            AlterColumn("dbo.Notifications", "message", c => c.String());
            AlterColumn("dbo.Ratings", "comment", c => c.String());
            AlterColumn("dbo.Ratings", "Service_Provider_id", c => c.Int());
            AlterColumn("dbo.Ratings", "service_provider_id", c => c.Int(nullable: false));
            CreateIndex("dbo.Bookings", "AppUser_id");
            CreateIndex("dbo.Bookings", "Bookable_id2");
            CreateIndex("dbo.Bookings", "Bookable_id3");
            CreateIndex("dbo.Bookings", "Bookable_id4");
            CreateIndex("dbo.Bookings", "Bookable1_id");
            CreateIndex("dbo.Bookings", "User_id2");
            CreateIndex("dbo.Bookings", "AppUser_id1");
            CreateIndex("dbo.Bookings", "AppUser_id2");
            CreateIndex("dbo.Bookables", "Location_id2");
            CreateIndex("dbo.Bookables", "Location_id3");
            CreateIndex("dbo.Bookables", "Location_id4");
            CreateIndex("dbo.Bookables", "Location1_id");
            CreateIndex("dbo.Locations", "file_id2");
            CreateIndex("dbo.Notifications", "AppUser_id");
            CreateIndex("dbo.Notifications", "User_id2");
            CreateIndex("dbo.Notifications", "AppUser_id1");
            CreateIndex("dbo.Notifications", "AppUser_id2");
            CreateIndex("dbo.Ratings", "AppUser_id1");
            CreateIndex("dbo.Ratings", "Service_Provider_id");
            CreateIndex("dbo.Ratings", "User_id2");
            CreateIndex("dbo.Ratings", "AppUser_id2");
            CreateIndex("dbo.Ratings", "AppUser_id3");
            AddForeignKey("dbo.Bookings", "AppUser_id", "dbo.AppUsers", "id");
            AddForeignKey("dbo.Bookings", "Bookable_id3", "dbo.Bookables", "id");
            AddForeignKey("dbo.Bookables", "Location_id3", "dbo.Locations", "id");
            AddForeignKey("dbo.Bookables", "Location1_id", "dbo.Locations", "id");
            AddForeignKey("dbo.Bookings", "Bookable1_id", "dbo.Bookables", "id");
            AddForeignKey("dbo.Bookings", "AppUser_id2", "dbo.AppUsers", "id");
            AddForeignKey("dbo.Notifications", "AppUser_id", "dbo.AppUsers", "id");
            AddForeignKey("dbo.Notifications", "AppUser_id2", "dbo.AppUsers", "id");
            AddForeignKey("dbo.Ratings", "AppUser_id1", "dbo.AppUsers", "id");
            AddForeignKey("dbo.Ratings", "AppUser_id3", "dbo.AppUsers", "id");
            AddForeignKey("dbo.Bookings", "AppUser_id1", "dbo.AppUsers", "id");
            AddForeignKey("dbo.Notifications", "AppUser_id1", "dbo.AppUsers", "id");
            AddForeignKey("dbo.Ratings", "AppUser_id2", "dbo.AppUsers", "id");
            AddForeignKey("dbo.Bookings", "Bookable_id4", "dbo.Bookables", "id");
            AddForeignKey("dbo.Bookings", "User_id2", "dbo.AppUsers", "id");
            AddForeignKey("dbo.Bookings", "Bookable_id2", "dbo.Bookables", "id");
            AddForeignKey("dbo.Bookables", "Location_id4", "dbo.Locations", "id");
            AddForeignKey("dbo.Bookables", "Location_id2", "dbo.Locations", "id");
            AddForeignKey("dbo.Locations", "file_id2", "dbo.Files", "id");
            AddForeignKey("dbo.Notifications", "User_id2", "dbo.AppUsers", "id");
            AddForeignKey("dbo.Ratings", "User_id2", "dbo.AppUsers", "id");
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.Ratings", "User_id2", "dbo.AppUsers");
            DropForeignKey("dbo.Notifications", "User_id2", "dbo.AppUsers");
            DropForeignKey("dbo.Locations", "file_id2", "dbo.Files");
            DropForeignKey("dbo.Bookables", "Location_id2", "dbo.Locations");
            DropForeignKey("dbo.Bookables", "Location_id4", "dbo.Locations");
            DropForeignKey("dbo.Bookings", "Bookable_id2", "dbo.Bookables");
            DropForeignKey("dbo.Bookings", "User_id2", "dbo.AppUsers");
            DropForeignKey("dbo.Bookings", "Bookable_id4", "dbo.Bookables");
            DropForeignKey("dbo.Ratings", "AppUser_id2", "dbo.AppUsers");
            DropForeignKey("dbo.Notifications", "AppUser_id1", "dbo.AppUsers");
            DropForeignKey("dbo.Bookings", "AppUser_id1", "dbo.AppUsers");
            DropForeignKey("dbo.Ratings", "AppUser_id3", "dbo.AppUsers");
            DropForeignKey("dbo.Ratings", "AppUser_id1", "dbo.AppUsers");
            DropForeignKey("dbo.Notifications", "AppUser_id2", "dbo.AppUsers");
            DropForeignKey("dbo.Notifications", "AppUser_id", "dbo.AppUsers");
            DropForeignKey("dbo.Bookings", "AppUser_id2", "dbo.AppUsers");
            DropForeignKey("dbo.Bookings", "Bookable1_id", "dbo.Bookables");
            DropForeignKey("dbo.Bookables", "Location1_id", "dbo.Locations");
            DropForeignKey("dbo.Bookables", "Location_id3", "dbo.Locations");
            DropForeignKey("dbo.Bookings", "Bookable_id3", "dbo.Bookables");
            DropForeignKey("dbo.Bookings", "AppUser_id", "dbo.AppUsers");
            DropIndex("dbo.Ratings", new[] { "AppUser_id3" });
            DropIndex("dbo.Ratings", new[] { "AppUser_id2" });
            DropIndex("dbo.Ratings", new[] { "User_id2" });
            DropIndex("dbo.Ratings", new[] { "Service_Provider_id" });
            DropIndex("dbo.Ratings", new[] { "AppUser_id1" });
            DropIndex("dbo.Notifications", new[] { "AppUser_id2" });
            DropIndex("dbo.Notifications", new[] { "AppUser_id1" });
            DropIndex("dbo.Notifications", new[] { "User_id2" });
            DropIndex("dbo.Notifications", new[] { "AppUser_id" });
            DropIndex("dbo.Locations", new[] { "file_id2" });
            DropIndex("dbo.Bookables", new[] { "Location1_id" });
            DropIndex("dbo.Bookables", new[] { "Location_id4" });
            DropIndex("dbo.Bookables", new[] { "Location_id3" });
            DropIndex("dbo.Bookables", new[] { "Location_id2" });
            DropIndex("dbo.Bookings", new[] { "AppUser_id2" });
            DropIndex("dbo.Bookings", new[] { "AppUser_id1" });
            DropIndex("dbo.Bookings", new[] { "User_id2" });
            DropIndex("dbo.Bookings", new[] { "Bookable1_id" });
            DropIndex("dbo.Bookings", new[] { "Bookable_id4" });
            DropIndex("dbo.Bookings", new[] { "Bookable_id3" });
            DropIndex("dbo.Bookings", new[] { "Bookable_id2" });
            DropIndex("dbo.Bookings", new[] { "AppUser_id" });
            AlterColumn("dbo.Ratings", "service_provider_id", c => c.Int());
            AlterColumn("dbo.Ratings", "Service_Provider_id", c => c.Int(nullable: false));
            AlterColumn("dbo.Ratings", "comment", c => c.String(nullable: false));
            AlterColumn("dbo.Notifications", "message", c => c.String(nullable: false));
            AlterColumn("dbo.Files", "file_location", c => c.String(nullable: false));
            AlterColumn("dbo.Files", "file_name", c => c.String(nullable: false));
            AlterColumn("dbo.Locations", "room", c => c.String(nullable: false));
            AlterColumn("dbo.Locations", "address2", c => c.String(nullable: false));
            AlterColumn("dbo.Locations", "address1", c => c.String(nullable: false));
            AlterColumn("dbo.Bookables", "booking_type", c => c.String(nullable: false));
            AlterColumn("dbo.Bookables", "max_occupancy", c => c.Int(nullable: false));
            AlterColumn("dbo.Bookables", "available_end_time", c => c.String(nullable: false));
            AlterColumn("dbo.Bookables", "available_start_time", c => c.String(nullable: false));
            AlterColumn("dbo.Bookables", "available_day", c => c.String(nullable: false));
            AlterColumn("dbo.Bookables", "description", c => c.String(nullable: false));
            AlterColumn("dbo.Bookables", "name", c => c.String(nullable: false));
            AlterColumn("dbo.AppUsers", "password", c => c.String(nullable: false));
            AlterColumn("dbo.AppUsers", "last_name", c => c.String(nullable: false));
            AlterColumn("dbo.AppUsers", "first_name", c => c.String(nullable: false));
            DropColumn("dbo.Ratings", "AppUser_id3");
            DropColumn("dbo.Ratings", "AppUser_id2");
            DropColumn("dbo.Ratings", "User_id2");
            DropColumn("dbo.Ratings", "AppUser_id1");
            DropColumn("dbo.Notifications", "AppUser_id2");
            DropColumn("dbo.Notifications", "AppUser_id1");
            DropColumn("dbo.Notifications", "User_id2");
            DropColumn("dbo.Notifications", "AppUser_id");
            DropColumn("dbo.Locations", "file_id2");
            DropColumn("dbo.Bookables", "Location1_id");
            DropColumn("dbo.Bookables", "Location_id4");
            DropColumn("dbo.Bookables", "Location_id3");
            DropColumn("dbo.Bookables", "Location_id2");
            DropColumn("dbo.Bookings", "AppUser_id2");
            DropColumn("dbo.Bookings", "AppUser_id1");
            DropColumn("dbo.Bookings", "User_id2");
            DropColumn("dbo.Bookings", "Bookable1_id");
            DropColumn("dbo.Bookings", "Bookable_id4");
            DropColumn("dbo.Bookings", "Bookable_id3");
            DropColumn("dbo.Bookings", "Bookable_id2");
            DropColumn("dbo.Bookings", "AppUser_id");
            CreateIndex("dbo.Ratings", "AppUser_id");
            CreateIndex("dbo.Ratings", "User_id1");
            CreateIndex("dbo.Ratings", "Service_Provider_id");
            CreateIndex("dbo.Notifications", "User_id1");
            CreateIndex("dbo.Locations", "file_id1");
            CreateIndex("dbo.Bookables", "Location_id1");
            CreateIndex("dbo.Bookings", "User_id1");
            CreateIndex("dbo.Bookings", "Bookable_id1");
            AddForeignKey("dbo.Ratings", "User_id1", "dbo.AppUsers", "id");
            AddForeignKey("dbo.Locations", "file_id1", "dbo.Files", "id");
            AddForeignKey("dbo.Bookables", "Location_id1", "dbo.Locations", "id");
            AddForeignKey("dbo.Bookings", "Bookable_id1", "dbo.Bookables", "id");
            AddForeignKey("dbo.Ratings", "AppUser_id", "dbo.AppUsers", "id");
            AddForeignKey("dbo.Notifications", "User_id1", "dbo.AppUsers", "id");
            AddForeignKey("dbo.Bookings", "User_id1", "dbo.AppUsers", "id");
        }
    }
}
