// <auto-generated />
namespace ITO5032_Assignment.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class migration65 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration65));
        
        string IMigrationMetadata.Id
        {
            get { return "202208150957176_migration65"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
