// <auto-generated />
namespace ITO5032_Assignment.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class migration7 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration7));
        
        string IMigrationMetadata.Id
        {
            get { return "202208152338511_migration7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
